### ISSUE TITLE
UIPickerView in the PanModalPresentable controller

### ISSUE THREAD

**Issue by ionsilviumihai** [slackhq/PanModal#9] opened 2019-03-19 20:19 UTC
### Description

Describe your issue here.

### What type of issue is this?
- [X] question

What is the best solution for having a simple UIViewController as a PanModalPresentable which has a UIPickerView as a UI element? When I scroll in the UIPickerView, the pan gesture is also triggered in PanModal/Controller/PanModalPresentationController.
Is there any possibility to limit the gesture only to some of the views in the hierarchy?

**Comment by tun57** [comment] 2019-03-20 02:18
Hey @ionsilviumihai, thanks for letting us know. We don't have a flexible solution for this in the current release, but we're pushing a change within the next few hours that should let you limit where the pan gesture begins. If you need this sooner, lmk.

The changes are here 👉 https://github.com/slackhq/PanModal/pull/10

Once it's merged in, you'll have access to the recognizer before it starts responding to changes - allowing you to do this:

```    func shouldRespond(to panModalGestureRecognizer: UIPanGestureRecognizer) -> Bool {
        let location = panModalGestureRecognizer.location(in: view)
        return ![yourPickerView].frame.contains(location)
    }```

**Comment by ionsilviumihai** [comment] 2019-03-20 11:25
@tun57 Brilliant! This is exactly what I need. Thanks a lot for the quick response and solution.

My solution was to not add the pan gesture on the entire container, but send a small view (like a header) through the PanModalPresentable protocol and add the pan gesture just for this view.

**Comment by tun57** [comment] 2019-03-20 21:08
@ionsilviumihai Glad to hear 😄. The library does not yet have the capability to return the exact container position during transitioning. However you can get the position of the container from `view.superview?.frame.origin.y` in `func willRespond(to panModalGestureRecognizer: UIPanGestureRecognizer)`. Will this work for you?

**Comment by TosinAF** [comment] 2019-03-22 19:26
Hi @ionsilviumihai, The PR has been merged and we have created a release tag. I am going to close this issue now, feel free to reopen if you have further questions, thanks!

**Comment by MikeGlotov** [comment] 2019-03-26 09:46
Hi, I'm using the latest version of pan modal and for some reason `func willRespond(to panModalGestureRecognizer: UIPanGestureRecognizer)` doesn't get called. One important note that I'm using [AloeStackView](https://github.com/airbnb/AloeStackView) which is a UIScrollView subclass. I wonder what could be the reason for the func not to be called. Would be glad to hear any thoughts from you guys.

**Comment by tun57** [comment] 2019-03-27 18:11
Hey @MikeGlotov, does `willRespond` get called when you drag the presentedView? Are you currently utilizing `shouldRespond`?

**Comment by MikeGlotov** [comment] 2019-03-27 18:19
> Hey @MikeGlotov, does `willRespond` get called when you drag the presentedView? Are you currently utilizing `shouldRespond`?

Hi, I'm using `shouldRespond` and I've defined `willRespond` as well. None of them are called for some reason.

**Comment by tun57** [comment] 2019-03-27 18:50
Strange.. in order to help get to the root of the issue, could you check the following so we can rule them out as the cause:

1) `shouldRepond` exists in `PanModalPresentable` (CocoaPods is still using a prev version)
2) Is your `viewController` a subclass of another `viewController` conforming to `PanModalPresentable`?
3) Are you able to drag the `presentedViewController` without `willRespond` being called?
4) Is `shouldRespond` called _at all_?
5) Are you using `shouldPrioritize`?

**Comment by MikeGlotov** [comment] 2019-03-29 07:01
Hey @tun57,

I started using `func shouldPrioritize(panModalGestureRecognizer: UIPanGestureRecognizer) -> Bool` and it seems to be working! Also, I'm able to drag `presentedViewController` without calling `willRespond`. I may suppose that this happens because VC is embedded into `UINavigationController`

**Comment by MikeGlotov** [comment] 2019-04-01 17:59
@tun57  hi,

I had some time to look at the code once again.
1. I don't see `shouldRespond` defined in zPanModalPresentable`.
2. I'm using a simple `UIViewController` subclass.
3. `willRespond` gets called every time I'm trying to drag VC.
4. See pt 1.
5. I've tried to use it, but it doesn't make any difference. Maybe I'm missing something.

**Comment by tun57** [comment] 2019-04-02 07:28
Hey @MikeGlotov, apologies for the delayed response.

If `shouldRespond` isn't defined in `PanModalPresentable` & you're using CocoaPods, you may be on an older version `1.0.2` - which we'll update shortly. Hopefully that should fix the issue, I'll post back here once it's live on Cocoapods. 

I've tested PanModal with the Example version of AloeStackView on the latest PanModal release `1.2` and it seems to work as expected.

Just a note, if you're using a `UINavigationController` and it was presented using PanModal, `willRespond` will only be called on the navigationController (the top most view in the hierarchy) and not on the individual child view controllers.

**Comment by TosinAF** [comment] 2019-04-05 05:00
Hi,

Going to close this in the meantime. Feel free to reopen the issue if still not resolved.

Thanks.

**Closed by TosinAF** 2019-04-05 05:00 UTC
